### ISSUE TITLE
App crashing on start

### ISSUE THREAD

**Issue by Mo7mud** [mertemir/crypto-ticker#1]
App crashing with error in logcat

`09-04 02:43:06.163 1002-1002/com.example.basics.cryptoticker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.basics.cryptoticker, PID: 1002
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)
        at android.view.View.draw(View.java:15321)
        at android.view.View.updateDisplayListIfDirty(View.java:14257)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.updateDisplayListIfDirty(View.java:14252)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.draw(View.java:15324)
        at android.view.View.updateDisplayListIfDirty(View.java:14257)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.draw(View.java:15324)
        at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
        at android.view.View.updateDisplayListIfDirty(View.java:14257)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.updateDisplayListIfDirty(View.java:14252)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.updateDisplayListIfDirty(View.java:14252)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.updateDisplayListIfDirty(View.java:14252)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.updateDisplayListIfDirty(View.java:14252)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.updateDisplayListIfDirty(View.java:14252)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.View.draw(View.java:15049)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.draw(View.java:15324)
        at android.widget.FrameLayout.draw(FrameLayout.java:598)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2653)
        at android.view.View.updateDisplayListIfDirty(View.java:14257)
        at android.view.View.getDisplayList(View.java:14279)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
    	at android.view.ThreadedRenderer.draw(Threa
`

**Comment by mertemir** [comment]
Yes, it's because of a bug in the library MPAndroidChart. Which you can find it at: https://github.com/PhilJay/MPAndroidChart/issues/2450

**Comment by Mo7mud** [comment]
Thank you very much
